Add pytest job to CI pipeline and dependencies to pyproject.toml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -415,3 +415,58 @@ jobs:
         run: |
           . .venv/bin/activate
           pre-commit run --hook-stage manual yamllint --all-files --show-diff-on-failure
+
+  pytest:
+    runs-on: ubuntu-latest
+    needs: prepare-tests
+    name: Run pytest
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2.3.4
+
+      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+        uses: actions/setup-python@v2.2.2
+        id: python
+        with:
+          python-version: ${{ env.DEFAULT_PYTHON }}
+
+      - name: Restore base Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v2.1.6
+        with:
+          path: .venv
+          key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{needs.prepare-base.outputs.python-key }}
+
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+
+      - name: Register Python problem matcher
+        run: |
+          echo "::add-matcher::.github/workflows/matchers/python.json"
+
+      - name: Install Pytest Annotation plugin
+        run: |
+          . .venv/bin/activate
+          # Ideally this should be part of our dependencies
+          # However this plugin is fairly new and doesn't run correctly
+          # on a non-GitHub environment.
+          pip install pytest-github-actions-annotate-failures
+
+      - name: Run pytest
+        run: |
+          . .venv/bin/activate
+          pytest \
+            -qq \
+            --timeout=9 \
+            --durations=10 \
+            -n auto \
+            --dist=loadfile \
+            --cov myhome \
+            --cov-report= \
+            -o console_output_style=count \
+            -p no:sugar
+          coverage xml
+
